server:
  port: 80          # 服务端口
eureka: 
  client:             # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中

    
feign:
  hystrix: 
    enabled: true
  compression:
    request:
      mime-types:             # 可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048  # 超过2048的字节进行压缩
spring:
  zipkin:
    base-url: http://zipkin.com:8601  # 所有的数据提交到此服务之中
  sleuth:
    sampler:
      percentage: 1.0   # 定义抽样比率，默认为0.1
  application:
    name: mldncloud-consumer
    
logging: 
  level:
    cn.mldn.mldncloud.service: DEBUG  # 定义显示转换信息的开发包与日志级别