spring:
  application:
    name: mldncloud-zuul-gateway                  # 定义微服务名称
server:
  port: 9501                                      # 服务端口

eureka:
  client:                                         # 客户端进行Eureka注册的配置
    service-url:                                  # 定义Eureka服务地址
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: gateway-9501.com                  # 显示主机名称
