spring:
  application:
    name: mldncloud-zuul-gateway                  # 定义微服务名称
server:
  port: 9501                                      # 服务端口

security:
  oauth2:
    client:                                   # 配置客户信息
      user-authorization-uri: http://oauth-server.com:8701/oauth/authorize
      access-token-uri: http://oauth-server.com:8701/oauth/token
      client-id: cmldn                        # 客户id
      client-secret: cjava                  # 客户密码
    resource:                                 # 配置资源访问
      user-info-uri: http://oauth-server.com:8701/user


zuul:
  prefix: /mldn-proxy          # 定义公共代理前缀
  ignored-services:             # 禁用微服务列表
    "*"
  routes: 
    mldncloud-dept-service: /dept-proxy/**
  sensitiveHeaders: Cookie,Set-Cookie


eureka:
  client:                                         # 客户端进行Eureka注册的配置
    service-url:                                  # 定义Eureka服务地址
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: gateway-9501.com                  # 显示主机名称
