spring:
  application:
    name: mldncloud-upload-service                  # 定义微服务名称
  http:
    multipart:
      enabled: true                   # 启用http上传处理
      max-file-size: 100MB            # 设置单个文件的最大长度
      max-request-size: 100MB       # 设置最大的请求文件的大小
      file-size-threshold: 1MB      # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
server: 
  port: 8101                                      # 服务端口

eureka:
  client:                                         # 客户端进行Eureka注册的配置
    service-url:                                  # 定义Eureka服务地址
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    instance-id: upload-8101.com                    # 显示主机名称

info:
  app.name: mldncloud-upload-service
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$

